# Generated by Django 4.1.7 on 2023-03-13 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access_key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_code', models.TextField()),
                ('feret_key', models.TextField()),
                ('licensed_to', models.CharField(max_length=500)),
                ('activated', models.BooleanField(default=True)),
                ('used_already', models.BooleanField(default=False)),
                ('first_use_date', models.DateField(default=datetime.datetime(2023, 3, 13, 17, 11, 1, 937057))),
                ('valid_for_days', models.IntegerField(default=0)),
                ('valid_till', models.TextField()),
                ('sequence', models.IntegerField()),
                ('user_macid', models.CharField(max_length=200)),
            ],
        ),
    ]
