# Generated by Django 4.2.4 on 2023-09-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access_key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_code', models.TextField(unique=True)),
                ('feret_key', models.TextField()),
                ('licensed_to', models.CharField(max_length=500)),
                ('activated', models.BooleanField(default=True)),
                ('used_already', models.BooleanField(default=False)),
                ('first_use_date', models.DateField(null=True)),
                ('valid_for_days', models.IntegerField(default=0)),
                ('valid_till', models.TextField()),
                ('sequence', models.IntegerField()),
                ('user_macid', models.CharField(max_length=200, null=True)),
                ('app_name', models.CharField(default='ira', max_length=200)),
            ],
        ),
    ]
