# Generated by Django 4.1.7 on 2023-03-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensor', '0002_alter_access_key_first_use_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_key',
            name='first_use_date',
            field=models.DateField(),
        ),
    ]
