# Generated by Django 4.1.7 on 2023-03-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensor', '0004_alter_access_key_first_use_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_key',
            name='pass_code',
            field=models.TextField(unique=True),
        ),
    ]
