# Generated by Django 4.1.7 on 2023-03-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensor', '0005_alter_access_key_pass_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='access_key',
            name='app_name',
            field=models.CharField(default='ira', max_length=200),
        ),
    ]
